/*
 * rsc.h — SysCalls (RSC) C bindings.
 * @generated from canonical.toml — DO NOT EDIT.
 */

#ifndef RSC_H
#define RSC_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef _WINDEF_
typedef void*    RSC_HANDLE;
typedef void*    RSC_PVOID;
typedef int32_t  RSC_NTSTATUS;
typedef uintptr_t RSC_SIZE_T;
typedef uintptr_t RSC_ULONG_PTR;
typedef uint8_t  RSC_BOOLEAN;
typedef uint8_t  RSC_UCHAR;
typedef uint16_t RSC_USHORT;
typedef uint32_t RSC_ULONG;
typedef uint64_t RSC_ULONG64;
#else
#define RSC_HANDLE    HANDLE
#define RSC_PVOID     PVOID
#define RSC_NTSTATUS  NTSTATUS
#define RSC_SIZE_T    SIZE_T
#define RSC_ULONG_PTR ULONG_PTR
#define RSC_BOOLEAN   BOOLEAN
#define RSC_UCHAR     UCHAR
#define RSC_USHORT    USHORT
#define RSC_ULONG     ULONG
#define RSC_ULONG64   ULONG64
#endif

#define RSC_STATUS_SUCCESS           ((RSC_NTSTATUS)0x00000000)
#define RSC_STATUS_UNSUCCESSFUL      ((RSC_NTSTATUS)0xC0000001)
#define RSC_STATUS_ACCESS_DENIED     ((RSC_NTSTATUS)0xC0000022)
#define RSC_STATUS_INVALID_HANDLE    ((RSC_NTSTATUS)0xC0000008)
#define RSC_STATUS_INVALID_PARAMETER ((RSC_NTSTATUS)0xC000000D)
#define RSC_STATUS_NO_MEMORY         ((RSC_NTSTATUS)0xC0000017)

#define RSC_PAGE_READONLY            0x02
#define RSC_PAGE_READWRITE           0x04
#define RSC_PAGE_EXECUTE_READ        0x20
#define RSC_PAGE_EXECUTE_READWRITE   0x40
#define RSC_MEM_COMMIT               0x00001000
#define RSC_MEM_RESERVE              0x00002000
#define RSC_MEM_RELEASE              0x00008000

/* ---- Function declarations ---- */

RSC_NTSTATUS RscNtAcceptConnectPort(RSC_HANDLE* PortHandle, void* PortContext, void* ConnectionRequest, uint8_t AcceptConnection, void* ServerView, void* ClientView);
RSC_NTSTATUS RscNtAccessCheck(void* SecurityDescriptor, RSC_HANDLE ClientToken, RSC_ULONG DesiredAccess, void* GenericMapping, void* PrivilegeSet, RSC_ULONG* PrivilegeSetLength, RSC_ULONG* GrantedAccess, RSC_NTSTATUS* AccessStatus);
RSC_NTSTATUS RscNtAccessCheckAndAuditAlarm(const RSC_PVOID* SubsystemName, void* HandleId, const RSC_PVOID* ObjectTypeName, const RSC_PVOID* ObjectName, void* SecurityDescriptor, RSC_ULONG DesiredAccess, void* GenericMapping, uint8_t ObjectCreation, RSC_ULONG* GrantedAccess, RSC_NTSTATUS* AccessStatus, uint8_t* GenerateOnClose);
RSC_NTSTATUS RscNtAccessCheckByType(void* SecurityDescriptor, void* PrincipalSelfSid, RSC_HANDLE ClientToken, RSC_ULONG DesiredAccess, void* ObjectTypeList, RSC_ULONG ObjectTypeListLength, void* GenericMapping, void* PrivilegeSet, RSC_ULONG* PrivilegeSetLength, RSC_ULONG* GrantedAccess, RSC_NTSTATUS* AccessStatus);
RSC_NTSTATUS RscNtAccessCheckByTypeAndAuditAlarm(const RSC_PVOID* SubsystemName, void* HandleId, const RSC_PVOID* ObjectTypeName, const RSC_PVOID* ObjectName, void* SecurityDescriptor, void* PrincipalSelfSid, RSC_ULONG DesiredAccess, RSC_ULONG AuditType, RSC_ULONG Flags, void* ObjectTypeList, RSC_ULONG ObjectTypeListLength, void* GenericMapping, uint8_t ObjectCreation, RSC_ULONG* GrantedAccess, RSC_NTSTATUS* AccessStatus, uint8_t* GenerateOnClose);
RSC_NTSTATUS RscNtAccessCheckByTypeResultList(void* SecurityDescriptor, void* PrincipalSelfSid, RSC_HANDLE ClientToken, RSC_ULONG DesiredAccess, void* ObjectTypeList, RSC_ULONG ObjectTypeListLength, void* GenericMapping, void* PrivilegeSet, RSC_ULONG* PrivilegeSetLength, RSC_ULONG* GrantedAccess, RSC_NTSTATUS* AccessStatus);
RSC_NTSTATUS RscNtAccessCheckByTypeResultListAndAuditAlarm(const RSC_PVOID* SubsystemName, void* HandleId, const RSC_PVOID* ObjectTypeName, const RSC_PVOID* ObjectName, void* SecurityDescriptor, void* PrincipalSelfSid, RSC_ULONG DesiredAccess, RSC_ULONG AuditType, RSC_ULONG Flags, void* ObjectTypeList, RSC_ULONG ObjectTypeListLength, void* GenericMapping, uint8_t ObjectCreation, RSC_ULONG* GrantedAccess, RSC_NTSTATUS* AccessStatus, uint8_t* GenerateOnClose);
RSC_NTSTATUS RscNtAccessCheckByTypeResultListAndAuditAlarmByHandle(const RSC_PVOID* SubsystemName, void* HandleId, RSC_HANDLE ClientToken, const RSC_PVOID* ObjectTypeName, const RSC_PVOID* ObjectName, void* SecurityDescriptor, void* PrincipalSelfSid, RSC_ULONG DesiredAccess, RSC_ULONG AuditType, RSC_ULONG Flags, void* ObjectTypeList, RSC_ULONG ObjectTypeListLength, void* GenericMapping, uint8_t ObjectCreation, RSC_ULONG* GrantedAccess, RSC_NTSTATUS* AccessStatus, uint8_t* GenerateOnClose);
RSC_NTSTATUS RscNtAcquireCrossVmMutant(RSC_HANDLE CrossVmMutant, int64_t* Timeout);
RSC_NTSTATUS RscNtAcquireProcessActivityReference(RSC_HANDLE* ActivityReferenceHandle, RSC_HANDLE ParentProcessHandle, RSC_ULONG ProcessActivityType);
RSC_NTSTATUS RscNtAddAtom(const uint16_t* AtomName, RSC_ULONG Length, void* Atom);
RSC_NTSTATUS RscNtAddAtomEx(const uint16_t* AtomName, RSC_ULONG Length, void* Atom, RSC_ULONG Flags);
RSC_NTSTATUS RscNtAddBootEntry(void* BootEntry, RSC_ULONG* Id);
RSC_NTSTATUS RscNtAddDriverEntry(void* DriverEntry, RSC_ULONG* Id);
RSC_NTSTATUS RscNtAdjustGroupsToken(RSC_HANDLE TokenHandle, uint8_t ResetToDefault, void* NewState, RSC_ULONG BufferLength, void* PreviousState, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtAdjustPrivilegesToken(RSC_HANDLE TokenHandle, uint8_t DisableAllPrivileges, void* NewState, RSC_ULONG BufferLength, void* PreviousState, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtAdjustTokenClaimsAndDeviceGroups(RSC_HANDLE TokenHandle, uint8_t UserResetToDefault, uint8_t DeviceResetToDefault, uint8_t DeviceGroupsResetToDefault, void* NewUserState, void* NewDeviceState, void* NewDeviceGroupsState, RSC_ULONG UserBufferLength, void* PreviousUserState, RSC_ULONG DeviceBufferLength, void* PreviousDeviceState, RSC_ULONG DeviceGroupsBufferLength, void* PreviousDeviceGroups, RSC_ULONG* UserReturnLength, RSC_ULONG* DeviceReturnLength, RSC_ULONG* DeviceGroupsReturnBufferLength);
RSC_NTSTATUS RscNtAlertMultipleThreadByThreadId(RSC_HANDLE* MultipleThreadId, RSC_ULONG Count, void* ExtendedParameters, RSC_ULONG ExtendedParameterCount);
RSC_NTSTATUS RscNtAlertResumeThread(RSC_HANDLE ThreadHandle, RSC_ULONG* PreviousSuspendCount);
RSC_NTSTATUS RscNtAlertThread(RSC_HANDLE ThreadHandle);
RSC_NTSTATUS RscNtAlertThreadByThreadId(RSC_HANDLE ThreadId);
RSC_NTSTATUS RscNtAlertThreadByThreadIdEx(RSC_HANDLE ThreadId, void* Lock);
RSC_NTSTATUS RscNtAllocateLocallyUniqueId(void* Luid);
RSC_NTSTATUS RscNtAllocateReserveObject(RSC_HANDLE* MemoryReserveHandle, void* ObjectAttributes, RSC_ULONG Type);
RSC_NTSTATUS RscNtAllocateUserPhysicalPages(RSC_HANDLE ProcessHandle, RSC_SIZE_T* NumberOfPages, RSC_SIZE_T* UserPfnArray);
RSC_NTSTATUS RscNtAllocateUserPhysicalPagesEx(RSC_HANDLE ProcessHandle, RSC_SIZE_T* NumberOfPages, RSC_SIZE_T* UserPfnArray, void* ExtendedParameters, RSC_ULONG ExtendedParameterCount);
RSC_NTSTATUS RscNtAllocateUuids(uint64_t* Time, RSC_ULONG* Range, RSC_ULONG* Sequence, void* Seed);
RSC_NTSTATUS RscNtAllocateVirtualMemory(RSC_HANDLE ProcessHandle, void** BaseAddress, RSC_SIZE_T ZeroBits, RSC_SIZE_T* RegionSize, RSC_ULONG AllocationType, RSC_ULONG PageProtection);
RSC_NTSTATUS RscNtAllocateVirtualMemoryEx(RSC_HANDLE ProcessHandle, void** BaseAddress, RSC_SIZE_T* RegionSize, RSC_ULONG AllocationType, RSC_ULONG PageProtection, void* ExtendedParameters, RSC_ULONG ExtendedParameterCount);
RSC_NTSTATUS RscNtAlpcAcceptConnectPort(RSC_HANDLE* PortHandle, RSC_HANDLE ConnectionPortHandle, RSC_ULONG Flags, RSC_PVOID* ObjectAttributes, void* PortAttributes, void* PortContext, void* ConnectionRequest, void* ConnectionMessageAttributes, uint8_t AcceptConnection);
RSC_NTSTATUS RscNtAlpcCancelMessage(RSC_HANDLE PortHandle, RSC_ULONG Flags, void* MessageContext);
RSC_NTSTATUS RscNtAlpcConnectPort(RSC_HANDLE* PortHandle, const RSC_PVOID* PortName, RSC_PVOID* ObjectAttributes, void* PortAttributes, RSC_ULONG Flags, void* RequiredServerSid, void* ConnectionMessage, RSC_SIZE_T* BufferLength, void* OutMessageAttributes, void* InMessageAttributes, int64_t* Timeout);
RSC_NTSTATUS RscNtAlpcConnectPortEx(RSC_HANDLE* PortHandle, RSC_PVOID* ConnectionPortObjectAttributes, RSC_PVOID* ClientPortObjectAttributes, void* PortAttributes, RSC_ULONG Flags, void* ServerSecurityRequirements, void* ConnectionMessage, RSC_SIZE_T* BufferLength, void* OutMessageAttributes, void* InMessageAttributes, int64_t* Timeout);
RSC_NTSTATUS RscNtAlpcCreatePort(RSC_HANDLE* PortHandle, RSC_PVOID* ObjectAttributes, void* PortAttributes);
RSC_NTSTATUS RscNtAlpcCreatePortSection(RSC_HANDLE PortHandle, RSC_ULONG Flags, RSC_HANDLE SectionHandle, RSC_SIZE_T SectionSize, void* AlpcSectionHandle, RSC_SIZE_T* ActualSectionSize);
RSC_NTSTATUS RscNtAlpcCreateResourceReserve(RSC_HANDLE PortHandle, RSC_ULONG Flags, RSC_SIZE_T MessageSize, RSC_ULONG* ResourceId);
RSC_NTSTATUS RscNtAlpcCreateSectionView(RSC_HANDLE PortHandle, RSC_ULONG Flags, void* ViewAttributes);
RSC_NTSTATUS RscNtAlpcCreateSecurityContext(RSC_HANDLE PortHandle, RSC_ULONG Flags, void* SecurityAttribute);
RSC_NTSTATUS RscNtAlpcDeletePortSection(RSC_HANDLE PortHandle, RSC_ULONG Flags, RSC_ULONG SectionHandle);
RSC_NTSTATUS RscNtAlpcDeleteResourceReserve(RSC_HANDLE PortHandle, RSC_ULONG Flags, RSC_ULONG ResourceId);
RSC_NTSTATUS RscNtAlpcDeleteSectionView(RSC_HANDLE PortHandle, RSC_ULONG Flags, void* ViewBase);
RSC_NTSTATUS RscNtAlpcDeleteSecurityContext(RSC_HANDLE PortHandle, RSC_ULONG Flags, RSC_ULONG ContextHandle);
RSC_NTSTATUS RscNtAlpcDisconnectPort(RSC_HANDLE PortHandle, RSC_ULONG Flags);
RSC_NTSTATUS RscNtAlpcImpersonateClientContainerOfPort(RSC_HANDLE PortHandle, void* Message, RSC_ULONG Flags);
RSC_NTSTATUS RscNtAlpcImpersonateClientOfPort(RSC_HANDLE PortHandle, void* Message, void* Flags);
RSC_NTSTATUS RscNtAlpcOpenSenderProcess(RSC_HANDLE* ProcessHandle, RSC_HANDLE PortHandle, void* PortMessage, RSC_ULONG Flags, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtAlpcOpenSenderThread(RSC_HANDLE* ThreadHandle, RSC_HANDLE PortHandle, void* PortMessage, RSC_ULONG Flags, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtAlpcQueryInformation(RSC_HANDLE PortHandle, RSC_ULONG PortInformationClass, void* PortInformation, RSC_ULONG Length, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtAlpcQueryInformationMessage(RSC_HANDLE PortHandle, void* PortMessage, RSC_ULONG MessageInformationClass, void* MessageInformation, RSC_ULONG Length, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtAlpcRevokeSecurityContext(RSC_HANDLE PortHandle, RSC_ULONG Flags, RSC_ULONG ContextHandle);
RSC_NTSTATUS RscNtAlpcSendWaitReceivePort(RSC_HANDLE PortHandle, RSC_ULONG Flags, void* SendMessage, void* SendMessageAttributes, void* ReceiveMessage, RSC_SIZE_T* BufferLength, void* ReceiveMessageAttributes, int64_t* Timeout);
RSC_NTSTATUS RscNtAlpcSetInformation(RSC_HANDLE PortHandle, RSC_ULONG PortInformationClass, void* PortInformation, RSC_ULONG Length);
RSC_NTSTATUS RscNtApphelpCacheControl(RSC_ULONG ServiceClass, void* ServiceContext);
RSC_NTSTATUS RscNtAreMappedFilesTheSame(void* File1MappedAsAnImage, void* File2MappedAsFile);
RSC_NTSTATUS RscNtAssignProcessToJobObject(RSC_HANDLE JobHandle, RSC_HANDLE ProcessHandle);
RSC_NTSTATUS RscNtAssociateWaitCompletionPacket(RSC_HANDLE WaitCompletionPacketHandle, RSC_HANDLE IoCompletionHandle, RSC_HANDLE TargetObjectHandle, void* KeyContext, void* ApcContext, RSC_NTSTATUS IoStatus, RSC_SIZE_T IoStatusInformation, uint8_t* AlreadySignaled);
RSC_NTSTATUS RscNtCallEnclave(void* Routine, void* Reserved, RSC_ULONG Flags, void** RoutineParamReturn);
RSC_NTSTATUS RscNtCallbackReturn(void* OutputBuffer, RSC_ULONG OutputLength, RSC_NTSTATUS Status);
RSC_NTSTATUS RscNtCancelIoFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock);
RSC_NTSTATUS RscNtCancelIoFileEx(RSC_HANDLE FileHandle, RSC_PVOID* IoRequestToCancel, RSC_PVOID* IoStatusBlock);
RSC_NTSTATUS RscNtCancelSynchronousIoFile(RSC_HANDLE ThreadHandle, RSC_PVOID* IoRequestToCancel, RSC_PVOID* IoStatusBlock);
RSC_NTSTATUS RscNtCancelTimer(RSC_HANDLE TimerHandle, uint8_t* CurrentState);
RSC_NTSTATUS RscNtCancelTimer2(RSC_HANDLE TimerHandle, void* Parameters);
RSC_NTSTATUS RscNtCancelWaitCompletionPacket(RSC_HANDLE WaitCompletionPacketHandle, uint8_t RemoveSignaledPacket);
RSC_NTSTATUS RscNtChangeProcessState(RSC_HANDLE ProcessStateChangeHandle, RSC_HANDLE ProcessHandle, void* StateChangeType, void* ExtendedInformation, RSC_SIZE_T ExtendedInformationLength, RSC_ULONG Reserved);
RSC_NTSTATUS RscNtChangeThreadState(RSC_HANDLE ThreadStateChangeHandle, RSC_HANDLE ThreadHandle, RSC_ULONG StateChangeType, void* ExtendedInformation, RSC_SIZE_T ExtendedInformationLength, RSC_ULONG Reserved);
RSC_NTSTATUS RscNtClearEvent(RSC_HANDLE EventHandle);
RSC_NTSTATUS RscNtClose(RSC_HANDLE Handle);
RSC_NTSTATUS RscNtCloseObjectAuditAlarm(const RSC_PVOID* SubsystemName, void* HandleId, uint8_t GenerateOnClose);
RSC_NTSTATUS RscNtCommitComplete(RSC_HANDLE EnlistmentHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtCommitEnlistment(RSC_HANDLE EnlistmentHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtCommitRegistryTransaction(RSC_HANDLE RegistryTransactionHandle, RSC_ULONG Flags);
RSC_NTSTATUS RscNtCommitTransaction(RSC_HANDLE TransactionHandle, uint8_t Wait);
RSC_NTSTATUS RscNtCompactKeys(RSC_ULONG Count, RSC_HANDLE KeyArray);
RSC_NTSTATUS RscNtCompareObjects(RSC_HANDLE FirstObjectHandle, RSC_HANDLE SecondObjectHandle);
RSC_NTSTATUS RscNtCompareSigningLevels(RSC_ULONG FirstSigningLevel, RSC_ULONG SecondSigningLevel);
RSC_NTSTATUS RscNtCompareTokens(RSC_HANDLE FirstTokenHandle, RSC_HANDLE SecondTokenHandle, uint8_t* Equal);
RSC_NTSTATUS RscNtCompleteConnectPort(RSC_HANDLE PortHandle);
RSC_NTSTATUS RscNtCompressKey(RSC_HANDLE KeyHandle);
RSC_NTSTATUS RscNtConnectPort(RSC_HANDLE* PortHandle, const RSC_PVOID* PortName, void* SecurityQos, void* ClientView, void* ServerView, RSC_ULONG* MaxMessageLength, void* ConnectionInformation, RSC_ULONG* ConnectionInformationLength);
RSC_NTSTATUS RscNtContinue(void* ContextRecord, uint8_t TestAlert);
RSC_NTSTATUS RscNtContinueEx(void* ContextRecord, void* ContinueArgument);
RSC_NTSTATUS RscNtConvertBetweenAuxiliaryCounterAndPerformanceCounter(uint8_t ConvertAuxiliaryToPerformanceCounter, uint64_t* PerformanceOrAuxiliaryCounterValue, uint64_t* ConvertedValue, uint64_t* ConversionError);
RSC_NTSTATUS RscNtCopyFileChunk(RSC_HANDLE SourceHandle, RSC_HANDLE DestinationHandle, RSC_HANDLE EventHandle, RSC_PVOID* IoStatusBlock, RSC_ULONG Length, int64_t* SourceOffset, int64_t* DestOffset, RSC_ULONG* SourceKey, RSC_ULONG* DestKey, RSC_ULONG Flags);
RSC_NTSTATUS RscNtCreateCpuPartition(RSC_HANDLE* CpuPartitionHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtCreateCrossVmEvent(RSC_HANDLE* CrossVmEvent, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_ULONG CrossVmEventFlags, void* VMID, void* ServiceID);
RSC_NTSTATUS RscNtCreateCrossVmMutant(RSC_HANDLE* EventHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_ULONG CrossVmEventFlags, void* VMID, void* ServiceID);
RSC_NTSTATUS RscNtCreateDebugObject(RSC_HANDLE* DebugObjectHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_ULONG Flags);
RSC_NTSTATUS RscNtCreateDirectoryObject(RSC_HANDLE* DirectoryHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtCreateDirectoryObjectEx(RSC_HANDLE* DirectoryHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_HANDLE ShadowDirectoryHandle, RSC_ULONG Flags);
RSC_NTSTATUS RscNtCreateEnclave(RSC_HANDLE ProcessHandle, void** BaseAddress, RSC_SIZE_T ZeroBits, RSC_SIZE_T Size, RSC_SIZE_T InitialCommitment, RSC_ULONG EnclaveType, void* EnclaveInformation, RSC_ULONG EnclaveInformationLength, RSC_ULONG* EnclaveError);
RSC_NTSTATUS RscNtCreateEnlistment(RSC_HANDLE* EnlistmentHandle, RSC_ULONG DesiredAccess, RSC_HANDLE ResourceManagerHandle, RSC_HANDLE TransactionHandle, RSC_PVOID* ObjectAttributes, RSC_ULONG CreateOptions, RSC_ULONG NotificationMask, void* EnlistmentKey);
RSC_NTSTATUS RscNtCreateEvent(RSC_HANDLE* EventHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_ULONG EventType, uint8_t InitialState);
RSC_NTSTATUS RscNtCreateEventPair(RSC_HANDLE* EventPairHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtCreateFile(RSC_HANDLE* FileHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_PVOID* IoStatusBlock, int64_t* AllocationSize, RSC_ULONG FileAttributes, RSC_ULONG ShareAccess, RSC_ULONG CreateDisposition, RSC_ULONG CreateOptions, void* EaBuffer, RSC_ULONG EaLength);
RSC_NTSTATUS RscNtCreateIRTimer(RSC_HANDLE* TimerHandle, RSC_ULONG* TimerId, RSC_ULONG DesiredAccess);
RSC_NTSTATUS RscNtCreateIoCompletion(RSC_HANDLE* IoCompletionHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_ULONG NumberOfConcurrentThreads);
RSC_NTSTATUS RscNtCreateIoRing(RSC_HANDLE* IoRingHandle, RSC_ULONG CreateParametersLength, void* CreateParameters, RSC_ULONG OutputParametersLength, void* OutputParameters);
RSC_NTSTATUS RscNtCreateJobObject(RSC_HANDLE* JobHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtCreateJobSet(RSC_ULONG NumJob, void* UserJobSet, RSC_ULONG Flags);
RSC_NTSTATUS RscNtCreateKey(RSC_HANDLE* KeyHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_ULONG TitleIndex, const RSC_PVOID* Class, RSC_ULONG CreateOptions, RSC_ULONG* Disposition);
RSC_NTSTATUS RscNtCreateKeyTransacted(RSC_HANDLE* KeyHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_ULONG TitleIndex, const RSC_PVOID* Class, RSC_ULONG CreateOptions, RSC_HANDLE TransactionHandle, RSC_ULONG* Disposition);
RSC_NTSTATUS RscNtCreateKeyedEvent(RSC_HANDLE* KeyedEventHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_ULONG Flags);
RSC_NTSTATUS RscNtCreateLowBoxToken(RSC_HANDLE* TokenHandle, RSC_HANDLE ExistingTokenHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, void* PackageSid, RSC_ULONG CapabilityCount, void* Capabilities, RSC_ULONG HandleCount, RSC_HANDLE* Handles);
RSC_NTSTATUS RscNtCreateMailslotFile(RSC_HANDLE* FileHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_PVOID* IoStatusBlock, RSC_ULONG CreateOptions, RSC_ULONG MailslotQuota, RSC_ULONG MaximumMessageSize, int64_t* ReadTimeout);
RSC_NTSTATUS RscNtCreateMutant(RSC_HANDLE* MutantHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, uint8_t InitialOwner);
RSC_NTSTATUS RscNtCreateNamedPipeFile(RSC_HANDLE* FileHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_PVOID* IoStatusBlock, RSC_ULONG ShareAccess, RSC_ULONG CreateDisposition, RSC_ULONG CreateOptions, RSC_ULONG NamedPipeType, RSC_ULONG ReadMode, RSC_ULONG CompletionMode, RSC_ULONG MaximumInstances, RSC_ULONG InboundQuota, RSC_ULONG OutboundQuota, int64_t* DefaultTimeout);
RSC_NTSTATUS RscNtCreatePagingFile(const RSC_PVOID* PageFileName, int64_t* MinimumSize, int64_t* MaximumSize, RSC_ULONG Priority);
RSC_NTSTATUS RscNtCreatePartition(RSC_HANDLE ParentPartitionHandle, RSC_HANDLE* PartitionHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtCreatePort(RSC_HANDLE* PortHandle, RSC_PVOID* ObjectAttributes, RSC_ULONG MaxConnectionInfoLength, RSC_ULONG MaxMessageLength, RSC_ULONG MaxPoolUsage);
RSC_NTSTATUS RscNtCreatePrivateNamespace(RSC_HANDLE* NamespaceHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, void* BoundaryDescriptor);
RSC_NTSTATUS RscNtCreateProcess(RSC_HANDLE* ProcessHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_HANDLE ParentProcess, uint8_t InheritObjectTable, RSC_HANDLE SectionHandle, RSC_HANDLE DebugPort, RSC_HANDLE TokenHandle);
RSC_NTSTATUS RscNtCreateProcessEx(RSC_HANDLE* ProcessHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_HANDLE ParentProcess, RSC_ULONG Flags, RSC_HANDLE SectionHandle, RSC_HANDLE DebugPort, RSC_HANDLE TokenHandle, RSC_ULONG Reserved);
RSC_NTSTATUS RscNtCreateProcessStateChange(RSC_HANDLE* ProcessStateChangeHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_HANDLE ProcessHandle, RSC_ULONG Reserved);
RSC_NTSTATUS RscNtCreateProfile(RSC_HANDLE* ProfileHandle, RSC_HANDLE Process, void* ProfileBase, RSC_SIZE_T ProfileSize, RSC_ULONG BucketSize, RSC_ULONG* Buffer, RSC_ULONG BufferSize, RSC_ULONG ProfileSource, RSC_ULONG Affinity);
RSC_NTSTATUS RscNtCreateProfileEx(RSC_HANDLE* ProfileHandle, RSC_HANDLE Process, void* ProfileBase, RSC_SIZE_T ProfileSize, RSC_ULONG BucketSize, RSC_ULONG* Buffer, RSC_ULONG BufferSize, RSC_ULONG ProfileSource, uint16_t GroupCount, void* GroupAffinity);
RSC_NTSTATUS RscNtCreateRegistryTransaction(RSC_HANDLE* RegistryTransactionHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjAttributes, RSC_ULONG CreateOptions);
RSC_NTSTATUS RscNtCreateResourceManager(RSC_HANDLE* ResourceManagerHandle, RSC_ULONG DesiredAccess, RSC_HANDLE TmHandle, void* RmGuid, RSC_PVOID* ObjectAttributes, RSC_ULONG CreateOptions, const RSC_PVOID* Description);
RSC_NTSTATUS RscNtCreateSection(RSC_HANDLE* SectionHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, int64_t* MaximumSize, RSC_ULONG SectionPageProtection, RSC_ULONG AllocationAttributes, RSC_HANDLE FileHandle);
RSC_NTSTATUS RscNtCreateSectionEx(RSC_HANDLE* SectionHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, int64_t* MaximumSize, RSC_ULONG SectionPageProtection, RSC_ULONG AllocationAttributes, RSC_HANDLE FileHandle, void* ExtendedParameters, RSC_ULONG ExtendedParameterCount);
RSC_NTSTATUS RscNtCreateSemaphore(RSC_HANDLE* SemaphoreHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, int32_t InitialCount, int32_t MaximumCount);
RSC_NTSTATUS RscNtCreateSymbolicLinkObject(RSC_HANDLE* LinkHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, const RSC_PVOID* LinkTarget);
RSC_NTSTATUS RscNtCreateThread(RSC_HANDLE* ThreadHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_HANDLE ProcessHandle, RSC_PVOID* ClientId, void* ThreadContext, void* InitialTeb, uint8_t CreateSuspended);
RSC_NTSTATUS RscNtCreateThreadEx(RSC_HANDLE* ThreadHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_HANDLE ProcessHandle, void* StartRoutine, void* Argument, RSC_ULONG CreateFlags, RSC_SIZE_T ZeroBits, RSC_SIZE_T StackSize, RSC_SIZE_T MaximumStackSize, void* AttributeList);
RSC_NTSTATUS RscNtCreateThreadStateChange(RSC_HANDLE* ThreadStateChangeHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_HANDLE ThreadHandle, RSC_ULONG Reserved);
RSC_NTSTATUS RscNtCreateTimer(RSC_HANDLE* TimerHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_ULONG TimerType);
RSC_NTSTATUS RscNtCreateTimer2(RSC_HANDLE* TimerHandle, RSC_ULONG* TimerId, void* ObjectAttributes, RSC_ULONG Attributes, RSC_ULONG DesiredAccess);
RSC_NTSTATUS RscNtCreateToken(RSC_HANDLE* TokenHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_ULONG Type, void* AuthenticationId, int64_t* ExpirationTime, void* User, void* Groups, void* Privileges, void* Owner, void* PrimaryGroup, void* DefaultDacl, void* Source);
RSC_NTSTATUS RscNtCreateTokenEx(RSC_HANDLE* TokenHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_ULONG Type, void* AuthenticationId, int64_t* ExpirationTime, void* User, void* Groups, void* Privileges, void* UserAttributes, void* DeviceAttributes, void* DeviceGroups, void* MandatoryPolicy, void* Owner, void* PrimaryGroup, void* DefaultDacl, void* Source);
RSC_NTSTATUS RscNtCreateTransaction(RSC_HANDLE* TransactionHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, void* Uow, RSC_HANDLE TmHandle, RSC_ULONG CreateOptions, RSC_ULONG IsolationLevel, RSC_ULONG IsolationFlags, int64_t* Timeout, const RSC_PVOID* Description);
RSC_NTSTATUS RscNtCreateTransactionManager(RSC_HANDLE* TmHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, const RSC_PVOID* LogFileName, RSC_ULONG CreateOptions, RSC_ULONG CommitStrength);
RSC_NTSTATUS RscNtCreateUserProcess(RSC_HANDLE* ProcessHandle, RSC_HANDLE* ThreadHandle, RSC_ULONG ProcessDesiredAccess, RSC_ULONG ThreadDesiredAccess, void* ProcessObjectAttributes, void* ThreadObjectAttributes, RSC_ULONG ProcessFlags, RSC_ULONG ThreadFlags, void* ProcessParameters, void* CreateInfo, void* AttributeList);
RSC_NTSTATUS RscNtCreateWaitCompletionPacket(RSC_HANDLE* WaitCompletionPacketHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtCreateWaitablePort(RSC_HANDLE* PortHandle, RSC_PVOID* ObjectAttributes, RSC_ULONG MaxConnectionInfoLength, RSC_ULONG MaxMessageLength, RSC_ULONG MaxPoolUsage);
RSC_NTSTATUS RscNtCreateWnfStateName(void* StateName, RSC_ULONG NameLifetime, RSC_ULONG DataScope, uint8_t PersistData, void* TypeId, RSC_ULONG MaximumStateSize, void* SecurityDescriptor);
RSC_NTSTATUS RscNtCreateWorkerFactory(RSC_HANDLE* WorkerFactoryHandleReturn, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_HANDLE CompletionPortHandle, RSC_HANDLE WorkerProcessHandle, void* StartRoutine, void* StartParameter, RSC_ULONG MaxThreadCount, RSC_SIZE_T StackReserve, RSC_SIZE_T StackCommit);
RSC_NTSTATUS RscNtDebugActiveProcess(RSC_HANDLE ProcessHandle, RSC_HANDLE DebugObjectHandle);
RSC_NTSTATUS RscNtDebugContinue(RSC_HANDLE DebugObjectHandle, RSC_PVOID* ClientId, RSC_NTSTATUS ContinueStatus);
RSC_NTSTATUS RscNtDelayExecution(uint8_t Alertable, int64_t* DelayInterval);
RSC_NTSTATUS RscNtDeleteAtom(RSC_ULONG Atom);
RSC_NTSTATUS RscNtDeleteBootEntry(RSC_ULONG Id);
RSC_NTSTATUS RscNtDeleteDriverEntry(RSC_ULONG Id);
RSC_NTSTATUS RscNtDeleteFile(void* ObjectAttributes);
RSC_NTSTATUS RscNtDeleteKey(RSC_HANDLE KeyHandle);
RSC_NTSTATUS RscNtDeleteObjectAuditAlarm(const RSC_PVOID* SubsystemName, void* HandleId, uint8_t GenerateOnClose);
RSC_NTSTATUS RscNtDeletePrivateNamespace(RSC_HANDLE NamespaceHandle);
RSC_NTSTATUS RscNtDeleteValueKey(RSC_HANDLE KeyHandle, const RSC_PVOID* ValueName);
RSC_NTSTATUS RscNtDeleteWnfStateData(void* StateName, void* ExplicitScope);
RSC_NTSTATUS RscNtDeleteWnfStateName(void* StateName);
RSC_NTSTATUS RscNtDeviceIoControlFile(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, RSC_ULONG IoControlCode, void* InputBuffer, RSC_ULONG InputBufferLength, void* OutputBuffer, RSC_ULONG OutputBufferLength);
RSC_NTSTATUS RscNtDirectGraphicsCall(RSC_ULONG InputBufferLength, void* InputBuffer, RSC_ULONG OutputBufferLength, void* OutputBuffer, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtDisableLastKnownGood(void);
RSC_NTSTATUS RscNtDisplayString(const RSC_PVOID* String);
RSC_NTSTATUS RscNtDrawText(const RSC_PVOID* Text);
RSC_NTSTATUS RscNtDuplicateObject(RSC_HANDLE SourceProcessHandle, RSC_HANDLE SourceHandle, RSC_HANDLE TargetProcessHandle, RSC_HANDLE* TargetHandle, RSC_ULONG DesiredAccess, RSC_ULONG HandleAttributes, RSC_ULONG Options);
RSC_NTSTATUS RscNtDuplicateToken(RSC_HANDLE ExistingTokenHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, uint8_t EffectiveOnly, RSC_ULONG Type, RSC_HANDLE* NewTokenHandle);
RSC_NTSTATUS RscNtEnableLastKnownGood(void);
RSC_NTSTATUS RscNtEnumerateBootEntries(void* Buffer, RSC_ULONG* BufferLength);
RSC_NTSTATUS RscNtEnumerateDriverEntries(void* Buffer, RSC_ULONG* BufferLength);
RSC_NTSTATUS RscNtEnumerateKey(RSC_HANDLE KeyHandle, RSC_ULONG Index, RSC_ULONG KeyInformationClass, void* KeyInformation, RSC_ULONG Length, RSC_ULONG* ResultLength);
RSC_NTSTATUS RscNtEnumerateSystemEnvironmentValuesEx(RSC_ULONG InformationClass, void* Buffer, RSC_ULONG* BufferLength);
RSC_NTSTATUS RscNtEnumerateTransactionObject(RSC_HANDLE RootObjectHandle, RSC_ULONG QueryType, void* ObjectCursor, RSC_ULONG ObjectCursorLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtEnumerateValueKey(RSC_HANDLE KeyHandle, RSC_ULONG Index, RSC_ULONG KeyValueInformationClass, void* KeyValueInformation, RSC_ULONG Length, RSC_ULONG* ResultLength);
RSC_NTSTATUS RscNtExtendSection(RSC_HANDLE SectionHandle, int64_t* NewSectionSize);
RSC_NTSTATUS RscNtFilterBootOption(RSC_ULONG FilterOperation, RSC_ULONG ObjectType, RSC_ULONG ElementType, void* Data, RSC_ULONG DataSize);
RSC_NTSTATUS RscNtFilterToken(RSC_HANDLE ExistingTokenHandle, RSC_ULONG Flags, void* SidsToDisable, void* PrivilegesToDelete, void* RestrictedSids, RSC_HANDLE* NewTokenHandle);
RSC_NTSTATUS RscNtFilterTokenEx(RSC_HANDLE ExistingTokenHandle, RSC_ULONG Flags, void* SidsToDisable, void* PrivilegesToDelete, void* RestrictedSids, RSC_ULONG DisableUserClaimsCount, const RSC_PVOID* UserClaimsToDisable, RSC_ULONG DisableDeviceClaimsCount, const RSC_PVOID* DeviceClaimsToDisable, void* DeviceGroupsToDisable, void* RestrictedUserAttributes, void* RestrictedDeviceAttributes, void* RestrictedDeviceGroups, RSC_HANDLE* NewTokenHandle);
RSC_NTSTATUS RscNtFindAtom(const uint16_t* AtomName, RSC_ULONG Length, void* Atom);
RSC_NTSTATUS RscNtFlushBuffersFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock);
RSC_NTSTATUS RscNtFlushBuffersFileEx(RSC_HANDLE FileHandle, RSC_ULONG Flags, void* Parameters, RSC_ULONG ParametersSize, RSC_PVOID* IoStatusBlock);
RSC_NTSTATUS RscNtFlushInstallUILanguage(RSC_ULONG InstallUILanguage, RSC_ULONG SetComittedFlag);
RSC_NTSTATUS RscNtFlushInstructionCache(RSC_HANDLE ProcessHandle, void* BaseAddress, RSC_SIZE_T RegionSize);
RSC_NTSTATUS RscNtFlushKey(RSC_HANDLE KeyHandle);
RSC_NTSTATUS RscNtFlushProcessWriteBuffers(void);
RSC_NTSTATUS RscNtFlushVirtualMemory(RSC_HANDLE ProcessHandle, void** BaseAddress, RSC_SIZE_T* RegionSize, RSC_PVOID* IoStatus);
RSC_NTSTATUS RscNtFlushWriteBuffer(void);
RSC_NTSTATUS RscNtFreeUserPhysicalPages(RSC_HANDLE ProcessHandle, RSC_SIZE_T* NumberOfPages, RSC_SIZE_T* UserPfnArray);
RSC_NTSTATUS RscNtFreeVirtualMemory(RSC_HANDLE ProcessHandle, void** BaseAddress, RSC_SIZE_T* RegionSize, RSC_ULONG FreeType);
RSC_NTSTATUS RscNtFreezeRegistry(RSC_ULONG TimeOutInSeconds);
RSC_NTSTATUS RscNtFreezeTransactions(int64_t* FreezeTimeout, int64_t* ThawTimeout);
RSC_NTSTATUS RscNtFsControlFile(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, RSC_ULONG FsControlCode, void* InputBuffer, RSC_ULONG InputBufferLength, void* OutputBuffer, RSC_ULONG OutputBufferLength);
RSC_NTSTATUS RscNtGetCachedSigningLevel(RSC_HANDLE File, RSC_ULONG* Flags, void* SigningLevel, uint8_t* Thumbprint, RSC_ULONG* ThumbprintSize, RSC_ULONG* ThumbprintAlgorithm);
RSC_NTSTATUS RscNtGetCompleteWnfStateSubscription(void* OldDescriptorStateName, uint64_t* OldSubscriptionId, RSC_ULONG OldDescriptorEventMask, RSC_ULONG OldDescriptorStatus, void* NewDeliveryDescriptor, RSC_ULONG DescriptorSize);
RSC_NTSTATUS RscNtGetContextThread(RSC_HANDLE ThreadHandle, void* ThreadContext);
RSC_ULONG RscNtGetCurrentProcessorNumber(void);
RSC_ULONG RscNtGetCurrentProcessorNumberEx(void* ProcessorNumber);
RSC_NTSTATUS RscNtGetDevicePowerState(RSC_HANDLE Device, void* State);
RSC_NTSTATUS RscNtGetMUIRegistryInfo(RSC_ULONG Flags, RSC_ULONG* DataSize, void* Data);
RSC_NTSTATUS RscNtGetNextProcess(RSC_HANDLE ProcessHandle, RSC_ULONG DesiredAccess, RSC_ULONG HandleAttributes, RSC_ULONG Flags, RSC_HANDLE* NewProcessHandle);
RSC_NTSTATUS RscNtGetNextThread(RSC_HANDLE ProcessHandle, RSC_HANDLE ThreadHandle, RSC_ULONG DesiredAccess, RSC_ULONG HandleAttributes, RSC_ULONG Flags, RSC_HANDLE* NewThreadHandle);
RSC_NTSTATUS RscNtGetNlsSectionPtr(RSC_ULONG SectionType, RSC_ULONG SectionData, void* ContextData, void** SectionPointer, RSC_ULONG* SectionSize);
RSC_NTSTATUS RscNtGetNotificationResourceManager(RSC_HANDLE ResourceManagerHandle, void* TransactionNotification, RSC_ULONG NotificationLength, int64_t* Timeout, RSC_ULONG* ReturnLength, RSC_ULONG Asynchronous, RSC_SIZE_T AsynchronousContext);
RSC_NTSTATUS RscNtGetWriteWatch(RSC_HANDLE ProcessHandle, RSC_ULONG Flags, void* BaseAddress, RSC_SIZE_T RegionSize, void** UserAddressArray, RSC_SIZE_T* EntriesInUserAddressArray, RSC_ULONG* Granularity);
RSC_NTSTATUS RscNtImpersonateAnonymousToken(RSC_HANDLE ThreadHandle);
RSC_NTSTATUS RscNtImpersonateClientOfPort(RSC_HANDLE PortHandle, void* Message);
RSC_NTSTATUS RscNtImpersonateThread(RSC_HANDLE ServerThreadHandle, RSC_HANDLE ClientThreadHandle, void* SecurityQos);
RSC_NTSTATUS RscNtInitializeEnclave(RSC_HANDLE ProcessHandle, void* BaseAddress, void* EnclaveInformation, RSC_ULONG EnclaveInformationLength, RSC_ULONG* EnclaveError);
RSC_NTSTATUS RscNtInitializeNlsFiles(void** BaseAddress, void* DefaultLocaleId, int64_t* DefaultCasingTableSize, RSC_ULONG* CurrentNLSVersion);
RSC_NTSTATUS RscNtInitializeRegistry(uint16_t BootCondition);
RSC_NTSTATUS RscNtInitiatePowerAction(void* SystemAction, RSC_ULONG LightestSystemState, RSC_ULONG Flags, uint8_t Asynchronous);
RSC_NTSTATUS RscNtIsProcessInJob(RSC_HANDLE ProcessHandle, RSC_HANDLE JobHandle);
uint8_t RscNtIsSystemResumeAutomatic(void);
RSC_NTSTATUS RscNtIsUILanguageComitted(void);
RSC_NTSTATUS RscNtListenPort(RSC_HANDLE PortHandle, void* ConnectionRequest);
RSC_NTSTATUS RscNtLoadDriver(const RSC_PVOID* DriverServiceName);
RSC_NTSTATUS RscNtLoadEnclaveData(RSC_HANDLE ProcessHandle, void* BaseAddress, void* Buffer, RSC_SIZE_T BufferSize, RSC_ULONG Protect, void* PageInformation, RSC_ULONG PageInformationLength, RSC_SIZE_T* NumberOfBytesWritten, RSC_ULONG* EnclaveError);
RSC_NTSTATUS RscNtLoadKey(RSC_PVOID* TargetKey, RSC_PVOID* SourceFile);
RSC_NTSTATUS RscNtLoadKey2(RSC_PVOID* TargetKey, RSC_PVOID* SourceFile, RSC_ULONG Flags);
RSC_NTSTATUS RscNtLoadKey3(RSC_PVOID* TargetKey, RSC_PVOID* SourceFile, RSC_ULONG Flags, void* ExtendedParameters, RSC_ULONG ExtendedParameterCount, RSC_ULONG DesiredAccess, RSC_HANDLE* RootHandle, void* Reserved);
RSC_NTSTATUS RscNtLoadKeyEx(RSC_PVOID* TargetKey, RSC_PVOID* SourceFile, RSC_ULONG Flags, RSC_HANDLE TrustClassKey, RSC_HANDLE Event, RSC_ULONG DesiredAccess, RSC_HANDLE* RootHandle, void* Reserved);
RSC_NTSTATUS RscNtLockFile(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, int64_t* ByteOffset, int64_t* Length, RSC_ULONG Key, uint8_t FailImmediately, uint8_t ExclusiveLock);
RSC_NTSTATUS RscNtLockProductActivationKeys(RSC_ULONG* pPrivateVer, RSC_ULONG* pSafeMode);
RSC_NTSTATUS RscNtLockRegistryKey(RSC_HANDLE KeyHandle);
RSC_NTSTATUS RscNtLockVirtualMemory(RSC_HANDLE ProcessHandle, void** BaseAddress, RSC_SIZE_T* RegionSize, RSC_ULONG MapType);
RSC_NTSTATUS RscNtMakePermanentObject(RSC_HANDLE Handle);
RSC_NTSTATUS RscNtMakeTemporaryObject(RSC_HANDLE Handle);
RSC_NTSTATUS RscNtManageHotPatch(RSC_ULONG HotPatchInformationClass, void* HotPatchInformation, RSC_ULONG HotPatchInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtManagePartition(RSC_HANDLE TargetHandle, RSC_HANDLE SourceHandle, void* PartitionInformationClass, void* PartitionInformation, RSC_ULONG PartitionInformationLength);
RSC_NTSTATUS RscNtMapCMFModule(RSC_ULONG What, RSC_ULONG Index, RSC_ULONG* CacheIndexOut, RSC_ULONG* CacheFlagsOut, RSC_ULONG* ViewSizeOut, void** BaseAddress);
RSC_NTSTATUS RscNtMapUserPhysicalPages(void* VirtualAddress, RSC_SIZE_T NumberOfPages, RSC_SIZE_T* UserPfnArray);
RSC_NTSTATUS RscNtMapUserPhysicalPagesScatter(void** VirtualAddresses, RSC_SIZE_T NumberOfPages, RSC_SIZE_T* UserPfnArray);
RSC_NTSTATUS RscNtMapViewOfSection(RSC_HANDLE SectionHandle, RSC_HANDLE ProcessHandle, void** BaseAddress, RSC_SIZE_T ZeroBits, RSC_SIZE_T CommitSize, int64_t* SectionOffset, RSC_SIZE_T* ViewSize, RSC_ULONG InheritDisposition, RSC_ULONG AllocationType, RSC_ULONG PageProtection);
RSC_NTSTATUS RscNtMapViewOfSectionEx(RSC_HANDLE SectionHandle, RSC_HANDLE ProcessHandle, void** BaseAddress, int64_t* SectionOffset, RSC_SIZE_T* ViewSize, RSC_ULONG AllocationType, RSC_ULONG PageProtection, void* ExtendedParameters, RSC_ULONG ExtendedParameterCount);
RSC_NTSTATUS RscNtModifyBootEntry(void* BootEntry);
RSC_NTSTATUS RscNtModifyDriverEntry(void* DriverEntry);
RSC_NTSTATUS RscNtNotifyChangeDirectoryFile(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, void* Buffer, RSC_ULONG Length, RSC_ULONG CompletionFilter, uint8_t WatchTree);
RSC_NTSTATUS RscNtNotifyChangeDirectoryFileEx(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, void* Buffer, RSC_ULONG Length, RSC_ULONG CompletionFilter, uint8_t WatchTree, RSC_ULONG DirectoryNotifyInformationClass);
RSC_NTSTATUS RscNtNotifyChangeKey(RSC_HANDLE KeyHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, RSC_ULONG CompletionFilter, uint8_t WatchTree, void* Buffer, RSC_ULONG BufferSize, uint8_t Asynchronous);
RSC_NTSTATUS RscNtNotifyChangeMultipleKeys(RSC_HANDLE MasterKeyHandle, RSC_ULONG Count, RSC_ULONG SubordinateObjects, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, RSC_ULONG CompletionFilter, uint8_t WatchTree, void* Buffer, RSC_ULONG BufferSize, uint8_t Asynchronous);
RSC_NTSTATUS RscNtNotifyChangeSession(RSC_HANDLE SessionHandle, RSC_ULONG ChangeSequenceNumber, int64_t* ChangeTimeStamp, RSC_ULONG Event, RSC_ULONG NewState, RSC_ULONG PreviousState, void* Payload, RSC_ULONG PayloadSize);
RSC_NTSTATUS RscNtOpenCpuPartition(RSC_HANDLE* CpuPartitionHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtOpenDirectoryObject(RSC_HANDLE* DirectoryHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtOpenEnlistment(RSC_HANDLE* EnlistmentHandle, RSC_ULONG DesiredAccess, RSC_HANDLE ResourceManagerHandle, void* EnlistmentGuid, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtOpenEvent(RSC_HANDLE* EventHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtOpenEventPair(RSC_HANDLE* EventPairHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtOpenFile(RSC_HANDLE* FileHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_PVOID* IoStatusBlock, RSC_ULONG ShareAccess, RSC_ULONG OpenOptions);
RSC_NTSTATUS RscNtOpenIoCompletion(RSC_HANDLE* IoCompletionHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtOpenJobObject(RSC_HANDLE* JobHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtOpenKey(RSC_HANDLE* KeyHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtOpenKeyEx(RSC_HANDLE* KeyHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_ULONG OpenOptions);
RSC_NTSTATUS RscNtOpenKeyTransacted(RSC_HANDLE* KeyHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_HANDLE TransactionHandle);
RSC_NTSTATUS RscNtOpenKeyTransactedEx(RSC_HANDLE* KeyHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, RSC_ULONG OpenOptions, RSC_HANDLE TransactionHandle);
RSC_NTSTATUS RscNtOpenKeyedEvent(RSC_HANDLE* KeyedEventHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtOpenMutant(RSC_HANDLE* MutantHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtOpenObjectAuditAlarm(const RSC_PVOID* SubsystemName, void* HandleId, const RSC_PVOID* ObjectTypeName, const RSC_PVOID* ObjectName, void* SecurityDescriptor, RSC_HANDLE ClientToken, RSC_ULONG DesiredAccess, RSC_ULONG GrantedAccess, void* Privileges, uint8_t ObjectCreation, uint8_t AccessGranted, uint8_t* GenerateOnClose);
RSC_NTSTATUS RscNtOpenPartition(RSC_HANDLE* PartitionHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtOpenPrivateNamespace(RSC_HANDLE* NamespaceHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, void* BoundaryDescriptor);
RSC_NTSTATUS RscNtOpenProcess(RSC_HANDLE* ProcessHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_PVOID* ClientId);
RSC_NTSTATUS RscNtOpenProcessToken(RSC_HANDLE ProcessHandle, RSC_ULONG DesiredAccess, RSC_HANDLE* TokenHandle);
RSC_NTSTATUS RscNtOpenProcessTokenEx(RSC_HANDLE ProcessHandle, RSC_ULONG DesiredAccess, RSC_ULONG HandleAttributes, RSC_HANDLE* TokenHandle);
RSC_NTSTATUS RscNtOpenRegistryTransaction(RSC_HANDLE* RegistryTransactionHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjAttributes);
RSC_NTSTATUS RscNtOpenResourceManager(RSC_HANDLE* ResourceManagerHandle, RSC_ULONG DesiredAccess, RSC_HANDLE TmHandle, void* ResourceManagerGuid, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtOpenSection(RSC_HANDLE* SectionHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtOpenSemaphore(RSC_HANDLE* SemaphoreHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtOpenSession(RSC_HANDLE* SessionHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtOpenSymbolicLinkObject(RSC_HANDLE* LinkHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes);
RSC_NTSTATUS RscNtOpenThread(RSC_HANDLE* ThreadHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes, RSC_PVOID* ClientId);
RSC_NTSTATUS RscNtOpenThreadToken(RSC_HANDLE ThreadHandle, RSC_ULONG DesiredAccess, uint8_t OpenAsSelf, RSC_HANDLE* TokenHandle);
RSC_NTSTATUS RscNtOpenThreadTokenEx(RSC_HANDLE ThreadHandle, RSC_ULONG DesiredAccess, uint8_t OpenAsSelf, RSC_ULONG HandleAttributes, RSC_HANDLE* TokenHandle);
RSC_NTSTATUS RscNtOpenTimer(RSC_HANDLE* TimerHandle, RSC_ULONG DesiredAccess, void* ObjectAttributes);
RSC_NTSTATUS RscNtOpenTransaction(RSC_HANDLE* TransactionHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, void* Uow, RSC_HANDLE TmHandle);
RSC_NTSTATUS RscNtOpenTransactionManager(RSC_HANDLE* TmHandle, RSC_ULONG DesiredAccess, RSC_PVOID* ObjectAttributes, const RSC_PVOID* LogFileName, void* TmIdentity, RSC_ULONG OpenOptions);
RSC_NTSTATUS RscNtPlugPlayControl(void* PnPControlClass, void* PnPControlData, RSC_ULONG PnPControlDataLength);
RSC_NTSTATUS RscNtPowerInformation(void* InformationLevel, void* InputBuffer, RSC_ULONG InputBufferLength, void* OutputBuffer, RSC_ULONG OutputBufferLength);
RSC_NTSTATUS RscNtPrePrepareComplete(RSC_HANDLE EnlistmentHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtPrePrepareEnlistment(RSC_HANDLE EnlistmentHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtPrepareComplete(RSC_HANDLE EnlistmentHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtPrepareEnlistment(RSC_HANDLE EnlistmentHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtPrivilegeCheck(RSC_HANDLE ClientToken, void* RequiredPrivileges, uint8_t* Result);
RSC_NTSTATUS RscNtPrivilegeObjectAuditAlarm(const RSC_PVOID* SubsystemName, void* HandleId, RSC_HANDLE ClientToken, RSC_ULONG DesiredAccess, void* Privileges, uint8_t AccessGranted);
RSC_NTSTATUS RscNtPrivilegedServiceAuditAlarm(const RSC_PVOID* SubsystemName, const RSC_PVOID* ServiceName, RSC_HANDLE ClientToken, void* Privileges, uint8_t AccessGranted);
RSC_NTSTATUS RscNtPropagationComplete(RSC_HANDLE ResourceManagerHandle, RSC_ULONG RequestCookie, RSC_ULONG BufferLength, void* Buffer);
RSC_NTSTATUS RscNtPropagationFailed(RSC_HANDLE ResourceManagerHandle, RSC_ULONG RequestCookie, RSC_NTSTATUS PropStatus);
RSC_NTSTATUS RscNtProtectVirtualMemory(RSC_HANDLE ProcessHandle, void** BaseAddress, RSC_SIZE_T* RegionSize, RSC_ULONG NewProtection, RSC_ULONG* OldProtection);
RSC_NTSTATUS RscNtPssCaptureVaSpaceBulk(RSC_HANDLE ProcessHandle, void* BaseAddress, void* BulkInformation, RSC_SIZE_T BulkInformationLength, RSC_SIZE_T* ReturnLength);
RSC_NTSTATUS RscNtPulseEvent(RSC_HANDLE EventHandle, int32_t* PreviousState);
RSC_NTSTATUS RscNtQueryAttributesFile(void* ObjectAttributes, void* FileInformation);
RSC_NTSTATUS RscNtQueryAuxiliaryCounterFrequency(uint64_t* AuxiliaryCounterFrequency);
RSC_NTSTATUS RscNtQueryBootEntryOrder(RSC_ULONG* Ids, RSC_ULONG* Count);
RSC_NTSTATUS RscNtQueryBootOptions(void* BootOptions, RSC_ULONG* BootOptionsLength);
RSC_NTSTATUS RscNtQueryDebugFilterState(RSC_ULONG ComponentId, RSC_ULONG Level);
RSC_NTSTATUS RscNtQueryDefaultLocale(uint8_t UserProfile, void* DefaultLocaleId);
RSC_NTSTATUS RscNtQueryDefaultUILanguage(RSC_ULONG* DefaultUILanguageId);
RSC_NTSTATUS RscNtQueryDirectoryFile(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, void* FileInformation, RSC_ULONG Length, RSC_ULONG FileInformationClass, uint8_t ReturnSingleEntry, const RSC_PVOID* FileName, uint8_t RestartScan);
RSC_NTSTATUS RscNtQueryDirectoryFileEx(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, void* FileInformation, RSC_ULONG Length, RSC_ULONG FileInformationClass, RSC_ULONG QueryFlags, const RSC_PVOID* FileName);
RSC_NTSTATUS RscNtQueryDirectoryObject(RSC_HANDLE DirectoryHandle, void* Buffer, RSC_ULONG Length, uint8_t ReturnSingleEntry, uint8_t RestartScan, RSC_ULONG* Context, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryDriverEntryOrder(RSC_ULONG* Ids, RSC_ULONG* Count);
RSC_NTSTATUS RscNtQueryEaFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock, void* Buffer, RSC_ULONG Length, uint8_t ReturnSingleEntry, void* EaList, RSC_ULONG EaListLength, RSC_ULONG* EaIndex, uint8_t RestartScan);
RSC_NTSTATUS RscNtQueryEvent(RSC_HANDLE EventHandle, RSC_ULONG EventInformationClass, void* EventInformation, RSC_ULONG EventInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryFullAttributesFile(void* ObjectAttributes, void* FileInformation);
RSC_NTSTATUS RscNtQueryInformationAtom(RSC_ULONG Atom, RSC_ULONG AtomInformationClass, void* AtomInformation, RSC_ULONG AtomInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationByName(void* ObjectAttributes, RSC_PVOID* IoStatusBlock, void* FileInformation, RSC_ULONG Length, RSC_ULONG FileInformationClass);
RSC_NTSTATUS RscNtQueryInformationCpuPartition(RSC_HANDLE CpuPartitionHandle, RSC_ULONG CpuPartitionInformationClass, void* CpuPartitionInformation, RSC_ULONG CpuPartitionInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationEnlistment(RSC_HANDLE EnlistmentHandle, RSC_ULONG EnlistmentInformationClass, void* EnlistmentInformation, RSC_ULONG EnlistmentInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock, void* FileInformation, RSC_ULONG Length, RSC_ULONG FileInformationClass);
RSC_NTSTATUS RscNtQueryInformationJobObject(RSC_HANDLE JobHandle, RSC_ULONG JobObjectInformationClass, void* JobObjectInformation, RSC_ULONG JobObjectInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationPort(RSC_HANDLE PortHandle, void* PortInformationClass, void* PortInformation, RSC_ULONG Length, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationProcess(RSC_HANDLE ProcessHandle, void* ProcessInformationClass, void* ProcessInformation, RSC_ULONG ProcessInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationResourceManager(RSC_HANDLE ResourceManagerHandle, RSC_ULONG ResourceManagerInformationClass, void* ResourceManagerInformation, RSC_ULONG ResourceManagerInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationThread(RSC_HANDLE ThreadHandle, RSC_ULONG ThreadInformationClass, void* ThreadInformation, RSC_ULONG ThreadInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationToken(RSC_HANDLE TokenHandle, RSC_ULONG TokenInformationClass, void* TokenInformation, RSC_ULONG TokenInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationTransaction(RSC_HANDLE TransactionHandle, RSC_ULONG TransactionInformationClass, void* TransactionInformation, RSC_ULONG TransactionInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationTransactionManager(RSC_HANDLE TransactionManagerHandle, RSC_ULONG TransactionManagerInformationClass, void* TransactionManagerInformation, RSC_ULONG TransactionManagerInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInformationWorkerFactory(RSC_HANDLE WorkerFactoryHandle, RSC_ULONG WorkerFactoryInformationClass, void* WorkerFactoryInformation, RSC_ULONG WorkerFactoryInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryInstallUILanguage(RSC_ULONG* InstallUILanguageId);
RSC_NTSTATUS RscNtQueryIntervalProfile(RSC_ULONG ProfileSource, RSC_ULONG* Interval);
RSC_NTSTATUS RscNtQueryIoCompletion(RSC_HANDLE IoCompletionHandle, RSC_ULONG IoCompletionInformationClass, void* IoCompletionInformation, RSC_ULONG IoCompletionInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryIoRingCapabilities(RSC_SIZE_T IoRingCapabilitiesLength, void* IoRingCapabilities);
RSC_NTSTATUS RscNtQueryKey(RSC_HANDLE KeyHandle, RSC_ULONG KeyInformationClass, void* KeyInformation, RSC_ULONG Length, RSC_ULONG* ResultLength);
RSC_NTSTATUS RscNtQueryLicenseValue(const RSC_PVOID* ValueName, RSC_ULONG* Type, void* Data, RSC_ULONG DataSize, RSC_ULONG* ResultDataSize);
RSC_NTSTATUS RscNtQueryMultipleValueKey(RSC_HANDLE KeyHandle, void* ValueEntries, RSC_ULONG EntryCount, void* ValueBuffer, RSC_ULONG* BufferLength, RSC_ULONG* RequiredBufferLength);
RSC_NTSTATUS RscNtQueryMutant(RSC_HANDLE MutantHandle, RSC_ULONG MutantInformationClass, void* MutantInformation, RSC_ULONG MutantInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryObject(RSC_HANDLE Handle, RSC_ULONG ObjectInformationClass, void* ObjectInformation, RSC_ULONG ObjectInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryOpenSubKeys(RSC_PVOID* TargetKey, RSC_ULONG* HandleCount);
RSC_NTSTATUS RscNtQueryOpenSubKeysEx(RSC_PVOID* TargetKey, RSC_ULONG BufferLength, void* Buffer, RSC_ULONG* RequiredSize);
RSC_NTSTATUS RscNtQueryPerformanceCounter(int64_t* PerformanceCounter, int64_t* PerformanceFrequency);
RSC_ULONG RscNtQueryPortInformationProcess(void);
RSC_NTSTATUS RscNtQueryQuotaInformationFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock, void* Buffer, RSC_ULONG Length, uint8_t ReturnSingleEntry, void* SidList, RSC_ULONG SidListLength, void* StartSid, uint8_t RestartScan);
RSC_NTSTATUS RscNtQuerySection(RSC_HANDLE SectionHandle, RSC_ULONG SectionInformationClass, void* SectionInformation, RSC_SIZE_T SectionInformationLength, RSC_SIZE_T* ReturnLength);
RSC_NTSTATUS RscNtQuerySecurityAttributesToken(RSC_HANDLE TokenHandle, const RSC_PVOID* Attributes, RSC_ULONG NumberOfAttributes, void* Buffer, RSC_ULONG Length, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQuerySecurityObject(RSC_HANDLE Handle, RSC_ULONG SecurityInformation, void* SecurityDescriptor, RSC_ULONG Length, RSC_ULONG* LengthNeeded);
RSC_NTSTATUS RscNtQuerySecurityPolicy(const RSC_PVOID* Policy, const RSC_PVOID* KeyName, const RSC_PVOID* ValueName, RSC_ULONG ValueType, void* Value, RSC_ULONG* ValueSize);
RSC_NTSTATUS RscNtQuerySemaphore(RSC_HANDLE SemaphoreHandle, RSC_ULONG SemaphoreInformationClass, void* SemaphoreInformation, RSC_ULONG SemaphoreInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQuerySymbolicLinkObject(RSC_HANDLE LinkHandle, RSC_PVOID* LinkTarget, RSC_ULONG* ReturnedLength);
RSC_NTSTATUS RscNtQuerySystemEnvironmentValue(const RSC_PVOID* VariableName, uint16_t* VariableValue, uint16_t ValueLength, uint16_t* ReturnLength);
RSC_NTSTATUS RscNtQuerySystemEnvironmentValueEx(const RSC_PVOID* VariableName, void* VendorGuid, void* Buffer, RSC_ULONG* BufferLength, RSC_ULONG* Attributes);
RSC_NTSTATUS RscNtQuerySystemInformation(RSC_ULONG SystemInformationClass, void* SystemInformation, RSC_ULONG SystemInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQuerySystemInformationEx(RSC_ULONG SystemInformationClass, void* InputBuffer, RSC_ULONG InputBufferLength, void* SystemInformation, RSC_ULONG SystemInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQuerySystemTime(int64_t* SystemTime);
RSC_NTSTATUS RscNtQueryTimer(RSC_HANDLE TimerHandle, RSC_ULONG TimerInformationClass, void* TimerInformation, RSC_ULONG TimerInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtQueryTimerResolution(RSC_ULONG* MaximumTime, RSC_ULONG* MinimumTime, RSC_ULONG* CurrentTime);
RSC_NTSTATUS RscNtQueryValueKey(RSC_HANDLE KeyHandle, const RSC_PVOID* ValueName, RSC_ULONG KeyValueInformationClass, void* KeyValueInformation, RSC_ULONG Length, RSC_ULONG* ResultLength);
RSC_NTSTATUS RscNtQueryVirtualMemory(RSC_HANDLE ProcessHandle, void* BaseAddress, RSC_ULONG MemoryInformationClass, void* MemoryInformation, RSC_SIZE_T MemoryInformationLength, RSC_SIZE_T* ReturnLength);
RSC_NTSTATUS RscNtQueryVolumeInformationFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock, void* FsInformation, RSC_ULONG Length, RSC_ULONG FsInformationClass);
RSC_NTSTATUS RscNtQueryWnfStateData(void* StateName, void* TypeId, void* ExplicitScope, void* ChangeStamp, void* Buffer, RSC_ULONG* BufferLength);
RSC_NTSTATUS RscNtQueryWnfStateNameInformation(void* StateName, RSC_ULONG NameInfoClass, void* ExplicitScope, void* Buffer, RSC_ULONG BufferLength);
RSC_NTSTATUS RscNtQueueApcThread(RSC_HANDLE ThreadHandle, void* ApcRoutine, void* ApcArgument1, void* ApcArgument2, void* ApcArgument3);
RSC_NTSTATUS RscNtQueueApcThreadEx(RSC_HANDLE ThreadHandle, RSC_HANDLE ReserveHandle, void* ApcRoutine, void* ApcArgument1, void* ApcArgument2, void* ApcArgument3);
RSC_NTSTATUS RscNtQueueApcThreadEx2(RSC_HANDLE ThreadHandle, RSC_HANDLE ReserveHandle, RSC_ULONG ApcFlags, void* ApcRoutine, void* ApcArgument1, void* ApcArgument2, void* ApcArgument3);
RSC_NTSTATUS RscNtRaiseException(void* ExceptionRecord, void* ContextRecord, uint8_t FirstChance);
RSC_NTSTATUS RscNtRaiseHardError(RSC_NTSTATUS ErrorStatus, RSC_ULONG NumberOfParameters, RSC_ULONG UnicodeStringParameterMask, RSC_SIZE_T* Parameters, RSC_ULONG ValidResponseOptions, RSC_ULONG* Response);
RSC_NTSTATUS RscNtReadFile(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, void* Buffer, RSC_ULONG Length, int64_t* ByteOffset, RSC_ULONG* Key);
RSC_NTSTATUS RscNtReadFileScatter(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, void* SegmentArray, RSC_ULONG Length, int64_t* ByteOffset, RSC_ULONG* Key);
RSC_NTSTATUS RscNtReadOnlyEnlistment(RSC_HANDLE EnlistmentHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtReadRequestData(RSC_HANDLE PortHandle, void* Message, RSC_ULONG DataEntryIndex, void* Buffer, RSC_SIZE_T BufferSize, RSC_SIZE_T* NumberOfBytesRead);
RSC_NTSTATUS RscNtReadVirtualMemory(RSC_HANDLE ProcessHandle, void* BaseAddress, void* Buffer, RSC_SIZE_T NumberOfBytesToRead, RSC_SIZE_T* NumberOfBytesRead);
RSC_NTSTATUS RscNtReadVirtualMemoryEx(RSC_HANDLE ProcessHandle, void* BaseAddress, void* Buffer, RSC_SIZE_T NumberOfBytesToRead, RSC_SIZE_T* NumberOfBytesRead, RSC_ULONG Flags);
RSC_NTSTATUS RscNtRecoverEnlistment(RSC_HANDLE EnlistmentHandle, void* EnlistmentKey);
RSC_NTSTATUS RscNtRecoverResourceManager(RSC_HANDLE ResourceManagerHandle);
RSC_NTSTATUS RscNtRecoverTransactionManager(RSC_HANDLE TransactionManagerHandle);
RSC_NTSTATUS RscNtRegisterProtocolAddressInformation(RSC_HANDLE ResourceManager, void* ProtocolId, RSC_ULONG ProtocolInformationSize, void* ProtocolInformation, RSC_ULONG CreateOptions);
RSC_NTSTATUS RscNtRegisterThreadTerminatePort(RSC_HANDLE PortHandle);
RSC_NTSTATUS RscNtReleaseKeyedEvent(RSC_HANDLE KeyedEventHandle, void* KeyValue, uint8_t Alertable, int64_t* Timeout);
RSC_NTSTATUS RscNtReleaseMutant(RSC_HANDLE MutantHandle, int32_t* PreviousCount);
RSC_NTSTATUS RscNtReleaseSemaphore(RSC_HANDLE SemaphoreHandle, int32_t ReleaseCount, int32_t* PreviousCount);
RSC_NTSTATUS RscNtReleaseWorkerFactoryWorker(RSC_HANDLE WorkerFactoryHandle);
RSC_NTSTATUS RscNtRemoveIoCompletion(RSC_HANDLE IoCompletionHandle, void** KeyContext, void** ApcContext, RSC_PVOID* IoStatusBlock, int64_t* Timeout);
RSC_NTSTATUS RscNtRemoveIoCompletionEx(RSC_HANDLE IoCompletionHandle, void* IoCompletionInformation, RSC_ULONG Count, RSC_ULONG* NumEntriesRemoved, int64_t* Timeout, uint8_t Alertable);
RSC_NTSTATUS RscNtRemoveProcessDebug(RSC_HANDLE ProcessHandle, RSC_HANDLE DebugObjectHandle);
RSC_NTSTATUS RscNtRenameKey(RSC_HANDLE KeyHandle, const RSC_PVOID* NewName);
RSC_NTSTATUS RscNtRenameTransactionManager(const RSC_PVOID* LogFileName, void* ExistingTransactionManagerGuid);
RSC_NTSTATUS RscNtReplaceKey(RSC_PVOID* NewFile, RSC_HANDLE TargetHandle, RSC_PVOID* OldFile);
RSC_NTSTATUS RscNtReplacePartitionUnit(const RSC_PVOID* TargetInstancePath, const RSC_PVOID* SpareInstancePath, RSC_ULONG Flags);
RSC_NTSTATUS RscNtReplyPort(RSC_HANDLE PortHandle, void* ReplyMessage);
RSC_NTSTATUS RscNtReplyWaitReceivePort(RSC_HANDLE PortHandle, void** PortContext, void* ReplyMessage, void* ReceiveMessage);
RSC_NTSTATUS RscNtReplyWaitReceivePortEx(RSC_HANDLE PortHandle, void** PortContext, void* ReplyMessage, void* ReceiveMessage, int64_t* Timeout);
RSC_NTSTATUS RscNtReplyWaitReplyPort(RSC_HANDLE PortHandle, void* ReplyMessage);
RSC_NTSTATUS RscNtRequestPort(RSC_HANDLE PortHandle, void* RequestMessage);
RSC_NTSTATUS RscNtRequestWaitReplyPort(RSC_HANDLE PortHandle, void* RequestMessage, void* ReplyMessage);
RSC_NTSTATUS RscNtResetEvent(RSC_HANDLE EventHandle, int32_t* PreviousState);
RSC_NTSTATUS RscNtResetWriteWatch(RSC_HANDLE ProcessHandle, void* BaseAddress, RSC_SIZE_T RegionSize);
RSC_NTSTATUS RscNtRestoreKey(RSC_HANDLE KeyHandle, RSC_HANDLE FileHandle, RSC_ULONG Flags);
RSC_NTSTATUS RscNtResumeProcess(RSC_HANDLE ProcessHandle);
RSC_NTSTATUS RscNtResumeThread(RSC_HANDLE ThreadHandle, RSC_ULONG* PreviousSuspendCount);
RSC_NTSTATUS RscNtRevertContainerImpersonation(void);
RSC_NTSTATUS RscNtRollbackComplete(RSC_HANDLE EnlistmentHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtRollbackEnlistment(RSC_HANDLE EnlistmentHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtRollbackRegistryTransaction(RSC_HANDLE RegistryTransactionHandle, RSC_ULONG Flags);
RSC_NTSTATUS RscNtRollbackTransaction(RSC_HANDLE TransactionHandle, uint8_t Wait);
RSC_NTSTATUS RscNtRollforwardTransactionManager(RSC_HANDLE TransactionManagerHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtSaveKey(RSC_HANDLE KeyHandle, RSC_HANDLE FileHandle);
RSC_NTSTATUS RscNtSaveKeyEx(RSC_HANDLE KeyHandle, RSC_HANDLE FileHandle, RSC_ULONG Format);
RSC_NTSTATUS RscNtSaveMergedKeys(RSC_HANDLE HighPrecedenceKeyHandle, RSC_HANDLE LowPrecedenceKeyHandle, RSC_HANDLE FileHandle);
RSC_NTSTATUS RscNtSecureConnectPort(RSC_HANDLE* PortHandle, const RSC_PVOID* PortName, void* SecurityQos, void* ClientView, void* RequiredServerSid, void* ServerView, RSC_ULONG* MaxMessageLength, void* ConnectionInformation, RSC_ULONG* ConnectionInformationLength);
RSC_NTSTATUS RscNtSerializeBoot(void);
RSC_NTSTATUS RscNtSetBootEntryOrder(RSC_ULONG* Ids, RSC_ULONG Count);
RSC_NTSTATUS RscNtSetBootOptions(void* BootOptions, RSC_ULONG FieldsToChange);
RSC_NTSTATUS RscNtSetCachedSigningLevel(RSC_ULONG Flags, RSC_ULONG InputSigningLevel, RSC_HANDLE* SourceFiles, RSC_ULONG SourceFileCount, RSC_HANDLE TargetFile);
RSC_NTSTATUS RscNtSetCachedSigningLevel2(RSC_ULONG Flags, RSC_ULONG InputSigningLevel, RSC_HANDLE* SourceFiles, RSC_ULONG SourceFileCount, RSC_HANDLE TargetFile, RSC_ULONG* CacheInformation);
RSC_NTSTATUS RscNtSetContextThread(RSC_HANDLE ThreadHandle, void* ThreadContext);
RSC_NTSTATUS RscNtSetDebugFilterState(RSC_ULONG ComponentId, RSC_ULONG Level, uint8_t State);
RSC_NTSTATUS RscNtSetDefaultHardErrorPort(RSC_HANDLE DefaultHardErrorPort);
RSC_NTSTATUS RscNtSetDefaultLocale(uint8_t UserProfile, RSC_ULONG DefaultLocaleId);
RSC_NTSTATUS RscNtSetDefaultUILanguage(RSC_ULONG DefaultUILanguageId);
RSC_NTSTATUS RscNtSetDriverEntryOrder(RSC_ULONG* Ids, RSC_ULONG Count);
RSC_NTSTATUS RscNtSetEaFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock, void* Buffer, RSC_ULONG Length);
RSC_NTSTATUS RscNtSetEvent(RSC_HANDLE EventHandle, int32_t* PreviousState);
RSC_NTSTATUS RscNtSetEventBoostPriority(RSC_HANDLE EventHandle);
RSC_NTSTATUS RscNtSetEventEx(RSC_HANDLE ThreadId, void* Lock);
RSC_NTSTATUS RscNtSetHighEventPair(RSC_HANDLE EventPairHandle);
RSC_NTSTATUS RscNtSetHighWaitLowEventPair(RSC_HANDLE EventPairHandle);
RSC_NTSTATUS RscNtSetIRTimer(RSC_HANDLE TimerHandle, int64_t* DueTime);
RSC_NTSTATUS RscNtSetInformationCpuPartition(RSC_HANDLE CpuPartitionHandle, RSC_ULONG CpuPartitionInformationClass, void* CpuPartitionInformation, RSC_ULONG CpuPartitionInformationLength);
RSC_NTSTATUS RscNtSetInformationDebugObject(RSC_HANDLE DebugObjectHandle, RSC_ULONG DebugObjectInformationClass, void* DebugInformation, RSC_ULONG DebugInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtSetInformationEnlistment(RSC_HANDLE EnlistmentHandle, RSC_ULONG EnlistmentInformationClass, void* EnlistmentInformation, RSC_ULONG EnlistmentInformationLength);
RSC_NTSTATUS RscNtSetInformationFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock, void* FileInformation, RSC_ULONG Length, RSC_ULONG FileInformationClass);
RSC_NTSTATUS RscNtSetInformationIoRing(RSC_HANDLE IoRingHandle, RSC_ULONG IoRingInformationClass, RSC_ULONG IoRingInformationLength, void* IoRingInformation);
RSC_NTSTATUS RscNtSetInformationJobObject(RSC_HANDLE JobHandle, RSC_ULONG JobObjectInformationClass, void* JobObjectInformation, RSC_ULONG JobObjectInformationLength);
RSC_NTSTATUS RscNtSetInformationKey(RSC_HANDLE KeyHandle, RSC_ULONG KeySetInformationClass, void* KeySetInformation, RSC_ULONG KeySetInformationLength);
RSC_NTSTATUS RscNtSetInformationObject(RSC_HANDLE Handle, RSC_ULONG ObjectInformationClass, void* ObjectInformation, RSC_ULONG ObjectInformationLength);
RSC_NTSTATUS RscNtSetInformationProcess(RSC_HANDLE ProcessHandle, void* ProcessInformationClass, void* ProcessInformation, RSC_ULONG ProcessInformationLength);
RSC_NTSTATUS RscNtSetInformationResourceManager(RSC_HANDLE ResourceManagerHandle, RSC_ULONG ResourceManagerInformationClass, void* ResourceManagerInformation, RSC_ULONG ResourceManagerInformationLength);
RSC_NTSTATUS RscNtSetInformationSymbolicLink(RSC_HANDLE LinkHandle, RSC_ULONG SymbolicLinkInformationClass, void* SymbolicLinkInformation, RSC_ULONG SymbolicLinkInformationLength);
RSC_NTSTATUS RscNtSetInformationThread(RSC_HANDLE ThreadHandle, RSC_ULONG ThreadInformationClass, void* ThreadInformation, RSC_ULONG ThreadInformationLength);
RSC_NTSTATUS RscNtSetInformationToken(RSC_HANDLE TokenHandle, RSC_ULONG TokenInformationClass, void* TokenInformation, RSC_ULONG TokenInformationLength);
RSC_NTSTATUS RscNtSetInformationTransaction(RSC_HANDLE TransactionHandle, RSC_ULONG TransactionInformationClass, void* TransactionInformation, RSC_ULONG TransactionInformationLength);
RSC_NTSTATUS RscNtSetInformationTransactionManager(RSC_HANDLE TmHandle, RSC_ULONG TransactionManagerInformationClass, void* TransactionManagerInformation, RSC_ULONG TransactionManagerInformationLength);
RSC_NTSTATUS RscNtSetInformationVirtualMemory(RSC_HANDLE ProcessHandle, RSC_ULONG VmInformationClass, RSC_SIZE_T NumberOfEntries, void* VirtualAddresses, void* VmInformation, RSC_ULONG VmInformationLength);
RSC_NTSTATUS RscNtSetInformationWorkerFactory(RSC_HANDLE WorkerFactoryHandle, RSC_ULONG WorkerFactoryInformationClass, void* WorkerFactoryInformation, RSC_ULONG WorkerFactoryInformationLength);
RSC_NTSTATUS RscNtSetIntervalProfile(RSC_ULONG Interval, RSC_ULONG Source);
RSC_NTSTATUS RscNtSetIoCompletion(RSC_HANDLE IoCompletionHandle, void* KeyContext, void* ApcContext, RSC_NTSTATUS IoStatus, RSC_SIZE_T IoStatusInformation);
RSC_NTSTATUS RscNtSetIoCompletionEx(RSC_HANDLE IoCompletionHandle, RSC_HANDLE IoCompletionPacketHandle, void* KeyContext, void* ApcContext, RSC_NTSTATUS IoStatus, RSC_SIZE_T IoStatusInformation);
RSC_NTSTATUS RscNtSetLdtEntries(RSC_ULONG Selector0, RSC_ULONG Entry0Low, RSC_ULONG Entry0Hi, RSC_ULONG Selector1, RSC_ULONG Entry1Low, RSC_ULONG Entry1Hi);
RSC_NTSTATUS RscNtSetLowEventPair(RSC_HANDLE EventPairHandle);
RSC_NTSTATUS RscNtSetLowWaitHighEventPair(RSC_HANDLE EventPairHandle);
RSC_NTSTATUS RscNtSetQuotaInformationFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock, void* Buffer, RSC_ULONG Length);
RSC_NTSTATUS RscNtSetSecurityObject(RSC_HANDLE Handle, RSC_ULONG SecurityInformation, void* SecurityDescriptor);
RSC_NTSTATUS RscNtSetSystemEnvironmentValue(const RSC_PVOID* VariableName, const RSC_PVOID* VariableValue);
RSC_NTSTATUS RscNtSetSystemEnvironmentValueEx(const RSC_PVOID* VariableName, void* VendorGuid, void* Buffer, RSC_ULONG BufferLength, RSC_ULONG Attributes);
RSC_NTSTATUS RscNtSetSystemInformation(RSC_ULONG SystemInformationClass, void* SystemInformation, RSC_ULONG SystemInformationLength);
RSC_NTSTATUS RscNtSetSystemPowerState(void* SystemAction, RSC_ULONG LightestSystemState, RSC_ULONG Flags);
RSC_NTSTATUS RscNtSetSystemTime(int64_t* SystemTime, int64_t* PreviousTime);
RSC_NTSTATUS RscNtSetThreadExecutionState(RSC_ULONG NewFlags, RSC_ULONG* PreviousFlags);
RSC_NTSTATUS RscNtSetTimer(RSC_HANDLE TimerHandle, int64_t* DueTime, void* TimerApcRoutine, void* TimerContext, uint8_t ResumeTimer, int32_t Period, uint8_t* PreviousState);
RSC_NTSTATUS RscNtSetTimer2(RSC_HANDLE TimerHandle, int64_t* DueTime, int64_t* Period, void* Parameters);
RSC_NTSTATUS RscNtSetTimerEx(RSC_HANDLE TimerHandle, RSC_ULONG TimerSetInformationClass, void* TimerSetInformation, RSC_ULONG TimerSetInformationLength);
RSC_NTSTATUS RscNtSetTimerResolution(RSC_ULONG DesiredTime, uint8_t SetResolution, RSC_ULONG* ActualTime);
RSC_NTSTATUS RscNtSetUuidSeed(void* Seed);
RSC_NTSTATUS RscNtSetValueKey(RSC_HANDLE KeyHandle, const RSC_PVOID* ValueName, RSC_ULONG TitleIndex, RSC_ULONG Type, void* Data, RSC_ULONG DataSize);
RSC_NTSTATUS RscNtSetVolumeInformationFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock, void* FsInformation, RSC_ULONG Length, RSC_ULONG FsInformationClass);
RSC_NTSTATUS RscNtSetWnfProcessNotificationEvent(RSC_HANDLE NotificationEvent);
RSC_NTSTATUS RscNtShutdownSystem(RSC_ULONG Action);
RSC_NTSTATUS RscNtShutdownWorkerFactory(RSC_HANDLE WorkerFactoryHandle, int32_t* PendingWorkerCount);
RSC_NTSTATUS RscNtSignalAndWaitForSingleObject(RSC_HANDLE SignalHandle, RSC_HANDLE WaitHandle, uint8_t Alertable, int64_t* Timeout);
RSC_NTSTATUS RscNtSinglePhaseReject(RSC_HANDLE EnlistmentHandle, int64_t* TmVirtualClock);
RSC_NTSTATUS RscNtStartProfile(RSC_HANDLE ProfileHandle);
RSC_NTSTATUS RscNtStopProfile(RSC_HANDLE ProfileHandle);
RSC_NTSTATUS RscNtSubmitIoRing(RSC_HANDLE IoRingHandle, RSC_ULONG Flags, RSC_ULONG WaitOperations, int64_t* Timeout);
RSC_NTSTATUS RscNtSubscribeWnfStateChange(void* StateName, RSC_ULONG ChangeStamp, RSC_ULONG EventMask, uint64_t* SubscriptionId);
RSC_NTSTATUS RscNtSuspendProcess(RSC_HANDLE ProcessHandle);
RSC_NTSTATUS RscNtSuspendThread(RSC_HANDLE ThreadHandle, RSC_ULONG* PreviousSuspendCount);
RSC_NTSTATUS RscNtSystemDebugControl(RSC_ULONG Command, void* InputBuffer, RSC_ULONG InputBufferLength, void* OutputBuffer, RSC_ULONG OutputBufferLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtTerminateEnclave(void* BaseAddress, RSC_ULONG Flags);
RSC_NTSTATUS RscNtTerminateJobObject(RSC_HANDLE JobHandle, RSC_NTSTATUS ExitStatus);
RSC_NTSTATUS RscNtTerminateProcess(RSC_HANDLE ProcessHandle, RSC_NTSTATUS ExitStatus);
RSC_NTSTATUS RscNtTerminateThread(RSC_HANDLE ThreadHandle, RSC_NTSTATUS ExitStatus);
RSC_NTSTATUS RscNtTestAlert(void);
RSC_NTSTATUS RscNtThawRegistry(void);
RSC_NTSTATUS RscNtThawTransactions(void);
RSC_NTSTATUS RscNtTraceControl(RSC_ULONG FunctionCode, void* InputBuffer, RSC_ULONG InputBufferLength, void* OutputBuffer, RSC_ULONG OutputBufferLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtTraceEvent(RSC_HANDLE TraceHandle, RSC_ULONG Flags, RSC_ULONG FieldSize, void* Fields);
RSC_NTSTATUS RscNtTranslateFilePath(void* InputFilePath, RSC_ULONG OutputType, void* OutputFilePath, RSC_ULONG* OutputFilePathLength);
RSC_NTSTATUS RscNtUmsThreadYield(void* SchedulerParam);
RSC_NTSTATUS RscNtUnloadDriver(const RSC_PVOID* DriverServiceName);
RSC_NTSTATUS RscNtUnloadKey(RSC_PVOID* TargetKey);
RSC_NTSTATUS RscNtUnloadKey2(RSC_PVOID* TargetKey, RSC_ULONG Flags);
RSC_NTSTATUS RscNtUnloadKeyEx(RSC_PVOID* TargetKey, RSC_HANDLE Event);
RSC_NTSTATUS RscNtUnlockFile(RSC_HANDLE FileHandle, RSC_PVOID* IoStatusBlock, int64_t* ByteOffset, int64_t* Length, RSC_ULONG Key);
RSC_NTSTATUS RscNtUnlockVirtualMemory(RSC_HANDLE ProcessHandle, void** BaseAddress, RSC_SIZE_T* RegionSize, RSC_ULONG MapType);
RSC_NTSTATUS RscNtUnmapViewOfSection(RSC_HANDLE ProcessHandle, void* BaseAddress);
RSC_NTSTATUS RscNtUnmapViewOfSectionEx(RSC_HANDLE ProcessHandle, void* BaseAddress, RSC_ULONG Flags);
RSC_NTSTATUS RscNtUnsubscribeWnfStateChange(void* StateName);
RSC_NTSTATUS RscNtUpdateWnfStateData(void* StateName, const RSC_ULONG** Buffer, RSC_ULONG Length, void* TypeId, void* ExplicitScope, RSC_ULONG MatchingChangeStamp, RSC_ULONG CheckStamp);
RSC_NTSTATUS RscNtVdmControl(RSC_ULONG Service, void* ServiceData);
RSC_NTSTATUS RscNtWaitForAlertByThreadId(void* Address, int64_t* Timeout);
RSC_NTSTATUS RscNtWaitForDebugEvent(RSC_HANDLE DebugObjectHandle, uint8_t Alertable, int64_t* Timeout, void* WaitStateChange);
RSC_NTSTATUS RscNtWaitForKeyedEvent(RSC_HANDLE KeyedEventHandle, void* KeyValue, uint8_t Alertable, int64_t* Timeout);
RSC_NTSTATUS RscNtWaitForMultipleObjects(RSC_ULONG Count, RSC_HANDLE Handles, RSC_ULONG WaitType, uint8_t Alertable, int64_t* Timeout);
RSC_NTSTATUS RscNtWaitForMultipleObjects32(RSC_ULONG Count, int32_t Handles, RSC_ULONG WaitType, uint8_t Alertable, int64_t* Timeout);
RSC_NTSTATUS RscNtWaitForSingleObject(RSC_HANDLE Handle, uint8_t Alertable, int64_t* Timeout);
RSC_NTSTATUS RscNtWaitForWorkViaWorkerFactory(RSC_HANDLE WorkerFactoryHandle, void* MiniPackets, RSC_ULONG Count, RSC_ULONG* PacketsReturned, void* DeferredWork);
RSC_NTSTATUS RscNtWaitHighEventPair(RSC_HANDLE EventPairHandle);
RSC_NTSTATUS RscNtWaitLowEventPair(RSC_HANDLE EventPairHandle);
RSC_NTSTATUS RscNtWorkerFactoryWorkerReady(RSC_HANDLE WorkerFactoryHandle);
RSC_NTSTATUS RscNtWow64AllocateVirtualMemory64(void* arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* arg7);
RSC_NTSTATUS RscNtWow64CallFunction64(void* arg1, void* arg2, void* arg3, void* arg4, void* arg5, void* arg6, void* arg7);
RSC_NTSTATUS RscNtWow64CsrAllocateCaptureBuffer(void* arg1, void* arg2);
RSC_NTSTATUS RscNtWow64CsrAllocateMessagePointer(void* arg1, void* arg2, void* arg3);
RSC_NTSTATUS RscNtWow64CsrCaptureMessageBuffer(void* arg1, void* arg2, void* arg3, void* arg4);
RSC_NTSTATUS RscNtWow64CsrCaptureMessageString(void* arg1, void* arg2, void* arg3, void* arg4, void* arg5);
RSC_NTSTATUS RscNtWow64CsrClientCallServer(void* arg1, void* arg2, void* arg3, void* arg4);
RSC_NTSTATUS RscNtWow64CsrClientConnectToServer(void* arg1, void* arg2, void* arg3, void* arg4, void* arg5);
RSC_NTSTATUS RscNtWow64CsrFreeCaptureBuffer(void* arg1);
RSC_NTSTATUS RscNtWow64CsrGetProcessId(void* arg1, void* arg2);
RSC_NTSTATUS RscNtWow64CsrIdentifyAlertableThread(void* arg1, void* arg2, void* arg3, void* arg4);
RSC_NTSTATUS RscNtWow64CsrVerifyRegion(void* arg1, void* arg2);
RSC_NTSTATUS RscNtWow64DebuggerCall(void* arg1, void* arg2, void* arg3, void* arg4, void* arg5);
RSC_NTSTATUS RscNtWow64GetCurrentProcessorNumber(void);
RSC_NTSTATUS RscNtWow64GetCurrentProcessorNumberEx(void* arg1);
RSC_NTSTATUS RscNtWow64GetNativeSystemInformation(RSC_ULONG SystemInformationClass, void* NativeSystemInformation, RSC_ULONG InformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtWow64IsProcessorFeaturePresent(void* arg1);
RSC_NTSTATUS RscNtWow64QueryInformationProcess64(RSC_HANDLE ProcessHandle, void* ProcessInformationClass, void* ProcessInformation, RSC_ULONG ProcessInformationLength, RSC_ULONG* ReturnLength);
RSC_NTSTATUS RscNtWow64ReadVirtualMemory64(RSC_HANDLE ProcessHandle, uint64_t BaseAddress, void* Buffer, uint64_t NumberOfBytesToRead, void* NumberOfBytesRead);
RSC_NTSTATUS RscNtWow64WriteVirtualMemory64(RSC_HANDLE ProcessHandle, uint64_t BaseAddress, void* Buffer, uint64_t NumberOfBytesToWrite, void* NumberOfBytesWritten);
RSC_NTSTATUS RscNtWriteFile(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, void* Buffer, RSC_ULONG Length, int64_t* ByteOffset, RSC_ULONG* Key);
RSC_NTSTATUS RscNtWriteFileGather(RSC_HANDLE FileHandle, RSC_HANDLE Event, void* ApcRoutine, void* ApcContext, RSC_PVOID* IoStatusBlock, void* SegmentArray, RSC_ULONG Length, int64_t* ByteOffset, RSC_ULONG* Key);
RSC_NTSTATUS RscNtWriteRequestData(RSC_HANDLE PortHandle, void* Message, RSC_ULONG DataEntryIndex, void* Buffer, RSC_SIZE_T BufferSize, RSC_SIZE_T* NumberOfBytesWritten);
RSC_NTSTATUS RscNtWriteVirtualMemory(RSC_HANDLE ProcessHandle, void* BaseAddress, void* Buffer, RSC_SIZE_T NumberOfBytesToWrite, RSC_SIZE_T* NumberOfBytesWritten);
RSC_NTSTATUS RscNtYieldExecution(void);

#ifdef __cplusplus
}
#endif

#endif /* RSC_H */
